name: Run ODH Notebook Controller unit tests
on:
  push:
  pull_request:
    paths:
      - components/common/**
      - components/notebook-controller/**
      - components/odh-notebook-controller/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        check-latest: true
        go-version-file: components/odh-notebook-controller/go.mod
        cache-dependency-path: components/odh-notebook-controller/go.sum

    - name: Run unit tests
      run: |
        cd components/odh-notebook-controller
        make test
